import React, { useState, useEffect } from 'react';
import { ExamSet } from './types/exam';
import { SAMPLE_EXAMS } from './data/sampleExams';
import { useClassroomSync } from './hooks/useClassroomSync';
import { TVDisplayView } from './components/TVDisplayView';
import { TeacherControllerView } from './components/TeacherControllerView';
import { TeacherAnswerKeyView } from './components/TeacherAnswerKeyView';
import { ExamGeneratorModal } from './components/ExamGeneratorModal';
import { PrintExamModal } from './components/PrintExamModal';
import { ExamBankModal } from './components/ExamBankModal';
import { SettingsModal } from './components/SettingsModal';
import {
  Tv,
  Radio,
  BookOpen,
  Sparkles,
  FolderOpen,
  Printer,
  ExternalLink,
  GraduationCap,
  Layers,
  HelpCircle,
  Settings,
} from 'lucide-react';

const SAVED_EXAMS_KEY = 'primary_exam_saved_bank';

export default function App() {
  // Check URL query parameters (e.g., ?view=tv for standalone TV window)
  const [isStandaloneTV, setIsStandaloneTV] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      if (params.get('view') === 'tv' || params.get('mode') === 'tv') {
        setIsStandaloneTV(true);
      }
    }
  }, []);

  // Saved exams list in localStorage
  const [savedExams, setSavedExams] = useState<ExamSet[]>(() => {
    if (typeof window !== 'undefined') {
      try {
        const stored = localStorage.getItem(SAVED_EXAMS_KEY);
        if (stored) {
          const parsed = JSON.parse(stored);
          if (Array.isArray(parsed) && parsed.length > 0) return parsed;
        }
      } catch (e) {}
    }
    return [];
  });

  // Current active exam (default to sample science exam)
  const [currentExam, setCurrentExam] = useState<ExamSet>(() => {
    if (typeof window !== 'undefined') {
      try {
        const stored = localStorage.getItem('primary_exam_current_active');
        if (stored) {
          return JSON.parse(stored);
        }
      } catch (e) {}
    }
    return SAMPLE_EXAMS[0];
  });

  // Save current active exam
  useEffect(() => {
    try {
      localStorage.setItem('primary_exam_current_active', JSON.stringify(currentExam));
    } catch (e) {}
  }, [currentExam]);

  // Classroom sync hook
  const {
    session,
    nextQuestion,
    prevQuestion,
    jumpToQuestion,
    toggleTimer,
    resetTimer,
    setTimerSeconds,
    setDefaultTimer,
    toggleRevealAnswer,
    voteChoice,
    resetVotes,
    updateActiveExam,
  } = useClassroomSync(currentExam, isStandaloneTV ? 'tv' : 'teacher');

  // Sync session when current exam changes
  useEffect(() => {
    updateActiveExam(currentExam);
  }, [currentExam.id]);

  // Active Main Tab: 'tv' | 'controller' | 'answer_key'
  const [activeTab, setActiveTab] = useState<'tv' | 'controller' | 'answer_key'>('controller');

  // Modals state
  const [isGeneratorOpen, setIsGeneratorOpen] = useState(false);
  const [isBankOpen, setIsBankOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [printModalConfig, setPrintModalConfig] = useState<{
    isOpen: boolean;
    mode: 'answer_key' | 'student_sheet' | 'exam_paper';
  }>({
    isOpen: false,
    mode: 'student_sheet',
  });

  // Toast notification
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Open TV in Pop-up / Second window
  const handleOpenTVWindow = () => {
    const url = `${window.location.origin}${window.location.pathname}?view=tv`;
    window.open(url, 'ClassroomTVWindow', 'width=1280,height=720,menubar=no,toolbar=no');
    showToast('เปิดหน้าจอทีวีในหน้าต่างใหม่เรียบร้อยแล้ว ลากไปยังจอทีวีหรือโปรเจกเตอร์ได้ทันที');
  };

  // Handle new exam generated by AI
  const handleExamGenerated = (newExam: ExamSet) => {
    setCurrentExam(newExam);
    setSavedExams((prev) => {
      const updated = [newExam, ...prev];
      try {
        localStorage.setItem(SAVED_EXAMS_KEY, JSON.stringify(updated));
      } catch (e) {}
      return updated;
    });
    updateActiveExam(newExam);
    setActiveTab('controller');
    showToast(`AI สร้างชุดข้อสอบ "${newExam.title}" (${newExam.questions.length} ข้อ) สำเร็จแล้ว!`);
  };

  // Delete saved exam
  const handleDeleteExam = (id: string) => {
    if (confirm('คุณต้องการลบชุดข้อสอบนี้ใช่หรือไม่?')) {
      setSavedExams((prev) => {
        const filtered = prev.filter((item) => item.id !== id);
        try {
          localStorage.setItem(SAVED_EXAMS_KEY, JSON.stringify(filtered));
        } catch (e) {}
        return filtered;
      });
    }
  };

  // Import exam
  const handleImportExam = (imported: ExamSet) => {
    setSavedExams((prev) => {
      const updated = [imported, ...prev];
      try {
        localStorage.setItem(SAVED_EXAMS_KEY, JSON.stringify(updated));
      } catch (e) {}
      return updated;
    });
    setCurrentExam(imported);
    updateActiveExam(imported);
    showToast(`นำเข้าชุดข้อสอบ "${imported.title}" สำเร็จ`);
  };

  // Standalone TV Mode (Clean fullscreen without headers or controls)
  if (isStandaloneTV) {
    return (
      <div className="w-full min-h-screen bg-slate-950 flex flex-col justify-center p-2 md:p-6">
        <TVDisplayView
          exam={currentExam}
          session={session}
          onNext={nextQuestion}
          onPrev={prevQuestion}
        />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed top-5 right-5 z-50 bg-gradient-to-r from-indigo-600 to-purple-600 text-white px-5 py-3 rounded-2xl shadow-2xl border border-indigo-400/40 text-sm font-semibold flex items-center gap-2 animate-bounce">
          <Sparkles className="w-4 h-4" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Main Top Navigation Header */}
      <header className="sticky top-0 z-40 bg-slate-900/90 backdrop-blur-md border-b border-slate-800 px-4 lg:px-8 py-3.5">
        <div className="max-w-7xl mx-auto flex flex-wrap items-center justify-between gap-4">
          {/* Logo & App Title */}
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-indigo-600 to-purple-600 flex items-center justify-center text-white shadow-lg shadow-indigo-600/30">
              <Tv className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="font-extrabold text-base md:text-lg text-white tracking-tight">
                  ระบบออกข้อสอบประถม & จอทีวี AI
                </h1>
                <span className="hidden sm:inline-block px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-[10px] font-bold border border-emerald-500/30">
                  ป.1 - ป.6
                </span>
              </div>
              <p className="text-xs text-slate-400 truncate max-w-xs md:max-w-md">
                {currentExam.grade} • {currentExam.subject} • {currentExam.title}
              </p>
            </div>
          </div>

          {/* Primary View Switcher Tabs (3 Modes) */}
          <div className="flex items-center p-1 bg-slate-950 rounded-2xl border border-slate-800">
            {/* Tab 1: Teacher Remote Controller */}
            <button
              onClick={() => setActiveTab('controller')}
              className={`flex items-center gap-2 px-3.5 md:px-5 py-2 rounded-xl text-xs md:text-sm font-bold transition-all ${
                activeTab === 'controller'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Radio className="w-4 h-4" />
              <span>รีโมทควบคุมครู</span>
            </button>

            {/* Tab 2: TV Display Screen */}
            <button
              onClick={() => setActiveTab('tv')}
              className={`flex items-center gap-2 px-3.5 md:px-5 py-2 rounded-xl text-xs md:text-sm font-bold transition-all ${
                activeTab === 'tv'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Tv className="w-4 h-4" />
              <span>หน้าจอทีวีห้องเรียน</span>
            </button>

            {/* Tab 3: Teacher Answer Key */}
            <button
              onClick={() => setActiveTab('answer_key')}
              className={`flex items-center gap-2 px-3.5 md:px-5 py-2 rounded-xl text-xs md:text-sm font-bold transition-all ${
                activeTab === 'answer_key'
                  ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <BookOpen className="w-4 h-4" />
              <span>หน้าเฉลยสำหรับครู</span>
            </button>
          </div>

          {/* Utility Tools: AI Generator, Bank, Popout TV, Print */}
          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsGeneratorOpen(true)}
              className="flex items-center gap-1.5 px-3.5 py-2 bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-500 hover:to-purple-500 text-white text-xs md:text-sm font-bold rounded-xl shadow-lg shadow-pink-600/20 transition-all hover:scale-[1.02]"
              title="สั่ง AI คิดข้อสอบ 20-40 ข้อ พร้อมเฉลย"
            >
              <Sparkles className="w-4 h-4" />
              <span>ออกข้อสอบด้วย AI</span>
            </button>

            <button
              onClick={() => setIsBankOpen(true)}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              title="คลังข้อสอบและสลับชุดข้อสอบ"
            >
              <FolderOpen className="w-5 h-5 text-indigo-400" />
            </button>

            <button
              onClick={handleOpenTVWindow}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              title="เปิดจอทีวีแยกหน้าต่าง สำหรับลากไปต่อทีวี/โปรเจกเตอร์"
            >
              <ExternalLink className="w-5 h-5 text-blue-400" />
            </button>

            <button
              onClick={() =>
                setPrintModalConfig({
                  isOpen: true,
                  mode: 'student_sheet',
                })
              }
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              title="พิมพ์กระดาษคำตอบ / ข้อสอบ"
            >
              <Printer className="w-5 h-5 text-amber-400" />
            </button>

            <button
              onClick={() => setIsSettingsOpen(true)}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors"
              title="ตั้งค่าโมเดล AI & API Keys (Gemini, OpenAI, Groq, OpenRouter, DeepSeek)"
            >
              <Settings className="w-5 h-5 text-slate-300 hover:text-white" />
            </button>
          </div>
        </div>
      </header>

      {/* Main Workspace Body */}
      <main className="flex-1 max-w-7xl mx-auto w-full p-4 md:p-6 lg:p-8">
        {/* View 1: Classroom TV Display View */}
        {activeTab === 'tv' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between bg-slate-900/60 px-4 py-2 rounded-xl border border-slate-800 text-xs text-slate-400">
              <span className="flex items-center gap-1.5">
                <Tv className="w-4 h-4 text-indigo-400" />
                โหมดแสดงเฉพาะข้อสอบสำหรับฉายขึ้นจอทีวี (นักเรียนจะเห็นเฉพาะโจทย์และตัวเลือก)
              </span>
              <button
                onClick={handleOpenTVWindow}
                className="text-indigo-400 hover:text-indigo-300 font-semibold flex items-center gap-1"
              >
                <span>เปิดในหน้าต่างแยกเพื่อฉายทีวี</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </button>
            </div>
            <TVDisplayView
              exam={currentExam}
              session={session}
              onNext={nextQuestion}
              onPrev={prevQuestion}
            />
          </div>
        )}

        {/* View 2: Teacher Remote Controller View */}
        {activeTab === 'controller' && (
          <TeacherControllerView
            exam={currentExam}
            session={session}
            onNext={nextQuestion}
            onPrev={prevQuestion}
            onJump={jumpToQuestion}
            onToggleTimer={toggleTimer}
            onResetTimer={resetTimer}
            onSetTimerSeconds={setTimerSeconds}
            onSetDefaultTimer={setDefaultTimer}
            onToggleReveal={toggleRevealAnswer}
            onVote={voteChoice}
            onResetVotes={resetVotes}
            onOpenTVWindow={handleOpenTVWindow}
            onSwitchToAnswerKey={() => setActiveTab('answer_key')}
          />
        )}

        {/* View 3: Teacher Answer Key View */}
        {activeTab === 'answer_key' && (
          <TeacherAnswerKeyView
            exam={currentExam}
            onJumpToQuestionOnTV={(index) => {
              jumpToQuestion(index);
              setActiveTab('tv');
              showToast(`ข้ามไปยังข้อ ${index + 1} บนจอทีวีแล้ว`);
            }}
            onOpenPrintModal={(mode) =>
              setPrintModalConfig({
                isOpen: true,
                mode,
              })
            }
          />
        )}
      </main>

      {/* Footer Info */}
      <footer className="no-print bg-slate-950 border-t border-slate-900 py-4 px-6 text-center text-xs text-slate-500">
        <p>
          ระบบข้อสอบประถมศึกษา ป.1 - ป.6 ตามหลักสูตรแกนกลางการศึกษาขั้นพื้นฐาน (สพฐ.) • พร้อม AI ช่วยออกข้อสอบและโหมดฉายจอทีวีห้องเรียน
        </p>
      </footer>

      {/* Modals */}
      <ExamGeneratorModal
        isOpen={isGeneratorOpen}
        onClose={() => setIsGeneratorOpen(false)}
        onExamGenerated={handleExamGenerated}
        onOpenSettings={() => {
          setIsGeneratorOpen(false);
          setIsSettingsOpen(true);
        }}
      />

      <ExamBankModal
        isOpen={isBankOpen}
        onClose={() => setIsBankOpen(false)}
        savedExams={savedExams}
        currentExamId={currentExam.id}
        onSelectExam={(exam) => {
          setCurrentExam(exam);
          updateActiveExam(exam);
          showToast(`เปลี่ยนเป็นชุดข้อสอบ "${exam.title}" แล้ว`);
        }}
        onDeleteExam={handleDeleteExam}
        onOpenGenerator={() => setIsGeneratorOpen(true)}
        onImportExam={handleImportExam}
      />

      <PrintExamModal
        isOpen={printModalConfig.isOpen}
        onClose={() => setPrintModalConfig({ isOpen: false, mode: 'student_sheet' })}
        exam={currentExam}
        mode={printModalConfig.mode}
      />

      <SettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
        onSettingsSaved={() => {
          showToast('บันทึกการตั้งค่าโมเดล AI & API Keys เรียบร้อยแล้ว');
        }}
      />
    </div>
  );
}
